require "piece"
require "ray"
require "position"
require "board"
require "ranged"

require "king"
require "queen"
require "knight"
require "bishop"
require "rook"
require "pieces"

require "piece_on_board"
require "moves_generator"
require "move"
